# Generated by Django 3.1.3 on 2020-12-07 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201206_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoescolar',
            name='peso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='eventoescolar',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_Escolar', to='core.member'),
        ),
    ]
